name: Juice Shop - Build, SBOM, Container Scan, SAST, Secret Scan

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  full_pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: |
        docker build -t juice-shop-custom .

    - name: Install Syft
      run: |
        curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

    - name: Generate SBOM with Syft
      run: |
        syft docker:juice-shop-custom -o json > sbom.json

    - name: Upload SBOM Artifact
      uses: actions/upload-artifact@v4
      with:
        name: sbom-file
        path: sbom.json

    - name: Install Grype
      run: |
        curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin

    - name: Scan Docker image with Grype
      continue-on-error: true
      run: |
        grype docker:juice-shop-custom -o json > grype-scan.json

    - name: Upload Grype Scan Artifact
      uses: actions/upload-artifact@v4
      with:
        name: grype-scan
        path: grype-scan.json

    - name: Install Semgrep
      run: |
        pip install semgrep

    - name: Run Semgrep and output SARIF
      continue-on-error: true
      run: |
        semgrep --config p/default --sarif > semgrep-results.sarif

    - name: Upload Semgrep SARIF Artifact
      uses: actions/upload-artifact@v4
      with:
        name: semgrep-sarif
        path: semgrep-results.sarif

    - name: Install Gitleaks
      run: |
        curl -sL https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks-linux-amd64 -o gitleaks
        chmod +x gitleaks
        sudo mv gitleaks /usr/local/bin/gitleaks

    - name: Run Gitleaks Secret Scan
      continue-on-error: true
      run: |
        gitleaks detect --source . --report-format
