name: Juice Shop - Build, SBOM, Container Scan, SAST, Secret Scan

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  full_pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Docker Build
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: |
        docker build -t juice-shop-custom .

    # Syft SBOM
    - name: Install Syft
      run: |
        curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

    - name: Generate SBOM with Syft
      run: |
        syft docker:juice-shop-custom -o json > sbom.json

    - name: Upload SBOM Artifact
      uses: actions/upload-artifact@v4
      with:
        name: sbom-file
        path: sbom.json

    # Grype Tarama
    - name: Install Grype
      run: |
        curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin

    - name: Scan Docker image with Grype
      run: |
        grype docker:juice-shop-custom -o json > grype-scan.json || true

    - name: Upload Grype Scan Artifact
      uses: actions/upload-artifact@v4
      with:
        name: grype-scan
        path: grype-scan.json

    # Semgrep ile SAST (SARIF)
    - name: Install Semgrep
      run: |
        pip install semgrep

    - name: Run Semgrep and output SARIF
      run: |
        semgrep --config p/default --sarif > semgrep-results.sarif || true

    - name: Upload Semgrep SARIF Artifact
      uses: actions/upload-artifact@v4
      with:
        name: semgrep-sarif
        path: semgrep-results.sarif

    # Gitleaks ile Secret Tarama
    - name: Install Gitleaks
      run: |
        curl -sSfL https://raw.githubusercontent.com/gitleaks/gitleaks/main/scripts/install.sh | bash

    - name: Run Gitleaks Secret Scan
      run: |
        gitleaks detect --source . --report-format sarif --report-path gitleaks-results.sarif || true

    - name: Upload Gitleaks SARIF Artifact
      uses: actions/upload-artifact@v4
      with:
        name: gitleaks-sarif
        path: gitleaks-results.sarif
